### ISSUE TITLE
Limit JVM memory usage?

### ISSUE THREAD

**Issue by naclander** [gjedeer/docker-elk-netflow#1]
How can I set the JVM Xmx and Xms values for logstash and elastcisearch? Is this possible using your container?

**Comment by gjedeer** [comment]
All the heavy lifting is done by https://elk-docker.readthedocs.io/ - this repo just adds the netflow plugin on top.

**Comment by gjedeer** [comment]
Seems to be possible: https://elk-docker.readthedocs.io/#overriding-variables
